# Generated by Django 4.1 on 2022-08-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                ("cod_conta", models.IntegerField(primary_key=True, serialize=False)),
                ("num_saldo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "conta",
            },
        ),
    ]
