# Generated by Django 4.1 on 2022-08-04 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={
                "db_table": "cliente",
            },
        ),
        migrations.RenameField(
            model_name="conta",
            old_name="cod_conta",
            new_name="conta",
        ),
        migrations.RenameField(
            model_name="conta",
            old_name="num_saldo",
            new_name="limite_credito",
        ),
        migrations.RemoveField(
            model_name="conta",
            name="email",
        ),
        migrations.AddField(
            model_name="conta",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conta",
            name="cliente",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="banco_api.cliente",
            ),
            preserve_default=False,
        ),
    ]
