# Generated by Django 4.1 on 2022-08-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0002_cliente_rename_cod_conta_conta_conta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conta",
            name="cliente",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Conta",
        ),
    ]
