# Generated by Django 4.1 on 2022-08-04 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banco_api", "0003_remove_conta_cliente_delete_cliente_delete_conta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cliente_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Conta",
            fields=[
                ("conta_id", models.AutoField(primary_key=True, serialize=False)),
                ("conta", models.IntegerField(unique=True)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "limite_credito",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credito_utilizado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("vencimento_fatura", models.DateField()),
                (
                    "cliente",
                    models.OneToOneField(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banco_api.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "contas",
            },
        ),
        migrations.CreateModel(
            name="TipoTransacao",
            fields=[
                ("codigo_tipo", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "movimentacao_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("data_movimentacao", models.DateField()),
                ("descricao", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "conta",
                    models.OneToOneField(
                        db_column="conta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="banco_api.conta",
                    ),
                ),
                (
                    "tipo_transacao",
                    models.OneToOneField(
                        db_column="codigo_tipo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="banco_api.tipotransacao",
                    ),
                ),
            ],
            options={
                "db_table": "movimentacoes",
            },
        ),
    ]
