# Generated by Django 4.1 on 2022-08-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="credito_utilizado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="conta",
            name="limite_credito",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="conta",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
