# Generated by Django 4.1 on 2022-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0005_alter_conta_credito_utilizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="vencimento_fatura",
            field=models.DateTimeField(null=True),
        ),
    ]
