# Generated by Django 4.1 on 2022-08-04 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0006_alter_conta_vencimento_fatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="conta",
            field=models.ForeignKey(
                db_column="conta",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="banco_api.conta",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_movimentacao",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo_transacao",
            field=models.ForeignKey(
                db_column="codigo_tipo",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="banco_api.tipotransacao",
            ),
        ),
    ]
