# Generated by Django 4.1 on 2022-08-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0007_alter_movimentacao_conta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusFatura",
            fields=[
                ("status_id", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "status_fatura",
            },
        ),
        migrations.AddField(
            model_name="conta",
            name="credito_ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Fatura",
            fields=[
                ("fatura_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(null=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_pagamento", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="banco_api.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "faturas",
            },
        ),
        migrations.AddField(
            model_name="conta",
            name="status_fatura",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="banco_api.statusfatura",
            ),
        ),
    ]
