# Generated by Django 4.1 on 2022-08-04 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0008_statusfatura_conta_credito_ativo_fatura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="data_abertura",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="data_pagamento",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="data_vencimento",
            field=models.DateTimeField(),
        ),
    ]
