# Generated by Django 4.1 on 2022-08-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0010_alter_fatura_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="cliente",
            field=models.ForeignKey(
                db_column="conta",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="banco_api.cliente",
            ),
        ),
    ]
