# Generated by Django 4.1 on 2022-08-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0012_alter_fatura_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fatura",
        ),
    ]
