# Generated by Django 4.1 on 2022-08-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0014_fatura"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fatura",
            old_name="cliente",
            new_name="conta",
        ),
    ]
