# Generated by Django 4.1 on 2022-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0017_alter_conta_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="conta",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="fatura",
            name="conta",
            field=models.IntegerField(),
        ),
    ]
