# Generated by Django 4.1 on 2022-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_api", "0018_alter_conta_conta_alter_fatura_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="conta",
            field=models.IntegerField(),
        ),
    ]
